### ISSUE TITLE
✨ The application should be a PWA

### ISSUE THREAD

**Issue by haavarol** [ecatch-kyst/web#11]
The application should be a progressive web application. This means that the application should:
- [x] be served over HTTPS
- [x] responsive on tablets & mobile devices
- [x] all app URLs load while offline
- [x] metadata provided for Add to Home screen
- [x] first load fast even on 3G
- [x] work cross-browser
- [x] have a URL for each page
- [x] transition between pages smoothly

For more information see here https://developers.google.com/web/progressive-web-apps/checklist

## Expected Behavior

The user should be able to use the application regardless of being connected to the internet or not. It should feel like an app.

## Priority

Fast

## Size

4

**Comment by balazsorban44** [comment]
#8

**Comment by balazsorban44** [comment]
This is something we must track and be sure to follow throughout the whole development, so I moved it to a further milestone.

**Comment by PetterRein** [comment]
PWA IS DONE!
