### ISSUE TITLE
✨ Send DEP message

### ISSUE THREAD

**Issue by haavarol** [ecatch-kyst/web#13]
The user needs to send a DEP message when leaving port.
## Expected Behavior

User should be able to send a message upon leaving the port. It should be a DEP message containing the fields listed [here](https://docs.google.com/document/d/136vO84bVtp69QuJNAc4qg69I2f3Ar4oKrJHQk22ZFhE/)
- [x] generate message
- [x] send message to firebase
- [x] notify user that message is sent

## Priority

Fast

## Size

3

**Comment by toretefre** [comment]
A basic UI for departure messages has now been created, and I will now figure out how to upload JSON to Firebase storage.

**Comment by balazsorban44** [comment]
Check this out! @toretefre  https://firebase.google.com/docs/firestore/manage-data/add-data#set_a_document

Just do `firebase.firestore().collection("messages").add(data)`

For convinience, check out this:

https://github.com/ecatch-kyst/web/blob/de9043ce0472198c0db231486e6f8df127893e90/src/lib/firebase.js#L24

I recommend you export  `MESSAGES_FS` collection reference here, that you can use elsewhere in the application. 

The `.add` operation returns a `Promise`, so don't forget to use `async/await`


This can be useful also: https://firebase.google.com/docs/firestore/manage-data/transactions

**Comment by toretefre** [comment]
Great stuff @balazsorban44, I'll do my best!

**Comment by balazsorban44** [comment]
Moving milestone up to Sprint 2, as it was not finished on time.

**Comment by toretefre** [comment]
PR #29 addresses two first objectives, Ebba currently working on status on sent messages so will not be implemented twice.
