### ISSUE TITLE
✨ Add Getting Started instructions to README

### ISSUE THREAD

**Issue by toretefre** [ecatch-kyst/web#19]
The README should contain instructions on how to get started for developers.

## Expected Behavior
Getting Started, Prerequisites and Setup should be present in README.md

## Priority
Should be implemented asap as it is very little work and essential for new developers to contribute

## Size
1 (approx 15 minutes)

**Comment by balazsorban44** [comment]
@toretefre  Please refer to the [CONTRIBUTING.md](https://github.com/ecatch-kyst/web/blob/master/CONTRIBUTING.md) instead. it holds all the necessary info. If you think it is not sufficient, please add your thoughts there, eventually you can link to it from the `README.md` to it. :wink:
