### ISSUE TITLE
🐛 dark mode toggle does not work

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#22]
## Expected Behavior

when clicking the dark mode toggle in the settings page, the colors should be changed
## Current Behavior

clicking the toggle, nothing happens
## Possible Solution

there is a `clickable` prop on a setting element, which also gets triggered when the toggle button is tapped
## Steps to Reproduce

1. go to settings page
2. click on the toggle on the right
## Context (Environment)

-

## Possible Implementation

Remove the action from the switch, as it is redundant, because of the `clickable` prop on the `Element`

**Comment by elfingar** [comment]
When i commented out 'onClick={handleToggleDarkMode}' in the Element and 'onClick={() => clickable && onClick()} style={{cursor: clickable ? "pointer" : ""}}' in the ListItem the toggle for dark-mode works.

Will at least do this for now on the dark-mode branch to see the changes im working on.
