### ISSUE TITLE
🐛 When refreshing any page in logged in state, the user is redirected

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#26]
## Expected Behavior

When logged in, and refreshing any page, the user should stay on the current page
## Current Behavior

When logged in, and refreshing any page, the user will be redirected to the dashboard

## Possible Solution

For a split second, `AUTH.currentUser` does not exist, which triggers the redirect first to the root, then to the dashboard.
Try to set a timeout to don't trigger the redirect, or find another solution.
## Steps to Reproduce

1. log in
2. open profile page
3. refresh
4. the refreshed page will redirect to the dashboard, even though it should stay on profile

**Comment by balazsorban44** [comment]
@ecatch-kyst/frontend anyone interested?

**Comment by balazsorban44** [comment]
Can be useful:
https://stackoverflow.com/questions/49091416/refresh-on-protected-routes-react-router-with-firebase-auth

**Comment by PetterRein** [comment]
The stackoverflow uses a function from react-redux.

But from what I can see adding the user.uuid to localStorage and also check for that and not only AUTH.currentUser can prevent the redirect that happens when AUTH.currentUser is false for a few ms

**Comment by balazsorban44** [comment]
was thinking about something like this:
![image](https://user-images.githubusercontent.com/18369201/53305025-7c0f7a00-387c-11e9-8600-3023f4794b96.png)

**Comment by Mortefal** [comment]
@Virkz Did you solve this issue in Sprint 2? If not what needs to be done?

**Comment by PetterRein** [comment]
Looking at it.

Will solve it this week, I now what to do now.

**Comment by PetterRein** [comment]
Stuck

Everything works fine when you are logged inn now.

The problem is that you also get the "spinner" if you not are logged inn and try to accsess a page that is protected because isLoading is True and AUTH.currentUser is False the same requirments for showing to spinner

**Comment by balazsorban44** [comment]
@Virkz 
This may help:
https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged

**Comment by PetterRein** [comment]
Spinner now work perfect
