### ISSUE TITLE
✨ Give feedback to user on message status

### ISSUE THREAD

**Issue by haavarol** [ecatch-kyst/web#31]
The user needs to be notified on the status of the message. I.e. if the message is saved in cache, sent to our server or received ACK from dualog.
## Expected Behavior

Give a feedback to user with a modal or something similar to make the status explicitly clear. 

## Priority

Fast

## Size

3

**Comment by elfingar** [comment]
@balazsorban44 Does this need to be a modal or could it just be the way it is today, by displaying the status on the messages page?

**Comment by balazsorban44** [comment]
Should ask the customer for clarification.

**Comment by Mortefal** [comment]
Are the icons we use on Trips / messagelist good enough for this issue to be done?

**Comment by balazsorban44** [comment]
No. The user should get an explicit notification, according to the customer.

**Comment by balazsorban44** [comment]
d0fe4a5
