### ISSUE TITLE
✨ Frontend DEP-melding

### ISSUE THREAD

**Issue by Mortefal** [ecatch-kyst/web#32]
- [x] Lage inputforms for å ta inn informasjon som fra bruker.

- [x] Legge inn informasjonen om fisk, fiskeredskap osv, på form, så det simplifiserer valgene bruker kan gjøre.

- [x] Skriv tester for alt. Bruk fornuften.

- [x] Send informasjonen til backend på riktig måte.

- [x] Sørg for at alt stemmer og skriv riktig commit-melding.

**Comment by balazsorban44** [comment]
Duplicate of #13? If not, maybe change the title, because it is too general.

**Comment by balazsorban44** [comment]
@Mortefal

**Comment by Mortefal** [comment]
Kan endre tittelen på det, og få merget den med det Tore jobbet med
