### ISSUE TITLE
✨ Show fish currently onboard

### ISSUE THREAD

**Issue by haavarol** [ecatch-kyst/web#33]
The user needs to be able to see how much fish currently is onboard.

## Progress

- [x] Create initial frontend
- [x] Fetch dynamic data from db
- [x] Display dynamic data nicely
- [x] Make sure only DCAs submitted after last DEP are included

## Expected Behavior

When the user is out fishing we should enable a view that presents the fish currently onboard.

## Priority

Fast

## Size

3

**Comment by balazsorban44** [comment]
@haavarol is this in Sprint 2? If so please add to the milestone

**Comment by haavarol** [comment]
@balazsorban44 that is correct. Fixed it.

**Comment by toretefre** [comment]
Moving up to Sprint 3 as feature will not be completed with sufficient quality and testing in Sprint 2.

**Comment by toretefre** [comment]
Will need proper DCA messages to complete this I think, will try to mock something.

**Comment by Mortefal** [comment]
What is the status here?

**Comment by toretefre** [comment]
Been working on the report this week and will continue on Monday I think!

Den lør. 16. mar. 2019, 18:53 skrev Mortefal <notifications@github.com>:

**Comment by toretefre** [comment]
Looking like this now. Please check issue description for remaining tasks.

![status](https://user-images.githubusercontent.com/21310942/54528123-4c83f700-497c-11e9-8e83-1be798c8bf8f.png)

**Comment by toretefre** [comment]
Is this needed or will it be replaced by the upcoming trips functionality? @balazsorban44

**Comment by toretefre** [comment]
Do you consider this issue as solved? @balazsorban44

**Comment by balazsorban44** [comment]
No, it is far from done, the new Trips view gives a good base to start, but nothing really has been implemented yet.

**Comment by PetterRein** [comment]
Done, we show fish onboard but not in a good way, but we do
