### ISSUE TITLE
🤯 Reminder to set Lighthouse threshold parameters

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#5]
## Description

As of now, @lighthousebot has no real thresholds set. We should figure out some good values/goals we should aim for, and set those in .travis.yml

Idea :bulb:: Check out some well-built, known PWAs' scores, and post them here in comments in the form of.:

> Website: http://example.com

> | Category | Score
> | ------------- | -------------
> | Performance | x
> | Progressive Web App | x |
> | Accessibility | x
> | Best Practices | x
> | SEO | x

(score template [here](https://gist.github.com/balazsorban44/bb7ce6be65975f0bfa559ac78a553eba))

@ecatch-kyst/frontend

**Comment by balazsorban44** [comment]
@ecatch-kyst/frontend

**Comment by elfingar** [comment]
I've looked into it a bit. I dont have any pwa examples, but from what i have read it seems like 80 is considered a good score and anything below means it can be optimized further. I dont know if that is an unrealistic goal or not to follow.

**Comment by toretefre** [comment]
Website: http://dev.opera.com

| Category | Score
| ------------- | -------------
| Performance | 95
| Progressive Web App | 81 |
| Accessibility | 76
| Best Practices | 93
| SEO | 100

Website: http://forbes.com

| Category | Score
| ------------- | -------------
| Performance | 32
| Progressive Web App | 31 |
| Accessibility | 87
| Best Practices | 73
| SEO | 100

Website: http://instagram.com

| Category | Score
| ------------- | -------------
| Performance | 58
| Progressive Web App | 62 |
| Accessibility | 77
| Best Practices | 100
| SEO | 80

Website: http://maps.google.com

| Category | Score
| ------------- | -------------
| Performance | 81
| Progressive Web App | 65 |
| Accessibility | 86
| Best Practices | 87
| SEO | 80

Website: http://offline-dino-game.firebaseapp.com

| Category | Score
| ------------- | -------------
| Performance | 100
| Progressive Web App | 100 |
| Accessibility | 93
| Best Practices | 87
| SEO | 91

Website: http://www.currency-calc.com/

| Category | Score
| ------------- | -------------
| Performance | 94
| Progressive Web App | 100 |
| Accessibility | 46
| Best Practices | 87
| SEO | 100

**Comment by toretefre** [comment]
Maybe we can try to beat Instagram on all fields except for Best Practices where we can aim for 75-80 which seems to be realistic?

**Comment by toretefre** [comment]
**eCatch Kyst Target?**
Website: http://ecatch-kyst-beta.firebaseapp.com

| Category | Score
| ------------- | -------------
| Performance | 60
| Progressive Web App | 60 |
| Accessibility | 80
| Best Practices | 70
| SEO | 80

**Comment by balazsorban44** [comment]
On Progressive Web App and Best Practices we can aim for 100, I think. PWA at least, since we build a PWA! In our case, SEO is much less important than best practices also, in my opinion. We don't have to "appeal" to anybody with our product, the main audition won't come through search engines.

EDIT: 
## My recommendation:
(using averages of the previous comment's results for Performance, and Accessibility)

**eCatch Kyst**
Website: http://ecatch-kyst-beta.firebaseapp.com

| Category | Score
| ------------- | -------------
| Performance | 77
| Progressive Web App | 100 |
| Accessibility | 78
| Best Practices | 100
| SEO | 1

**Comment by toretefre** [comment]
Closed in PR #44
