### ISSUE TITLE
✨ Send DCA message by midnight

### ISSUE THREAD

**Issue by Mortefal** [ecatch-kyst/web#51]
The user should get help from the system if he has not sent a DCA message before midnight
## Expected Behavior

If a fisher has sent a DEP message, but no DCA message before 12.00pm, the system should automaticly send a message for him.

- [ ] Fisherman should get a notification 5 minutes prior.
- [ ] Fisherman should get a notification that the message has been sent
- [ ] Fisherman should be certain that the message has integrity
- [ ] Fisherman should be certain that the message is empty when sent.
- [ ] Tests, backend and frontend

 

## Priority

Slow
Needs fully working DCA to be relevant

## Size

2

**Comment by toretefre** [comment]
Moved the issue to the backend repo
