### ISSUE TITLE
✨ Personalization of inputs

### ISSUE THREAD

**Issue by Mortefal** [ecatch-kyst/web#52]
A user should be able to predefine certain choices and options in the application
## Expected Behavior

- [x] User should be able to preset Homeport
- [x] User should be able to preset Main species (hovedmålarter)
- [x] User should be able to preset fishing tools
- [ ] User should be able to preset fishing tools specifications
- [x] User should be able to preset fishing spots
- [x] User should be able to preset fishing activity
- [x] User should be able to preset fish landing site
- [ ] The information needs to be verified.
- [x] Current position should be preset
- [ ] Tests

## Priority

medium / fast

## Size

4-5

**Comment by balazsorban44** [comment]
@Mortefal  @toretefre  @tordsta 

You can look at the [`feature/preset-values`](https://github.com/ecatch-kyst/web/tree/feature/preset-values) branch. Especially the [`Form.jsx`](https://github.com/ecatch-kyst/web/blob/feature/preset-values/src/components/Forms/Form.jsx) file. Any comments on it?

My idea is to retrieve information from the last message, and populate the currently opened form with the data.

**Comment by Mortefal** [comment]
It looks like a good starting point :+1: 

I have an idea that the fisher can create a group called "Bifangst", where he can add all the typical side catch, that only exists as a group. So when he selects the group from the dropdown, all fishtypes in the group gets added to the catch report.

For fishing gear and typical fishing types he can select from the options and these will be shown above the other options in a category called "My favorites" or something similar.

One idea is to remove all personaliziation from the Forms and have its own page that the user can use.

Dont know what you guys think about it

**Comment by PetterRein** [comment]
First version of preset values in Dropdown is now working in:
[Favorite-dropdown](/github/ecatch-kyst/web/tree/feature/favorite-in-dropdown)

**Comment by balazsorban44** [comment]
Bifangst won't be fixed because of lack of time.
