### ISSUE TITLE
🤯 Update locales

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#57]
## Description
The team has received a list of translations for expressions related to the app, in English 🇬🇧 , and Norwegian 🇳🇴. The [locales](https://github.com/ecatch-kyst/web/tree/master/src/locales) should be updated accordingly.

NOTE: Please, don't just add new translations headlessly, as it would cause chaos later. We will add new translations when they are needed. Only update existing translations.

[BabelEdit](https://www.codeandweb.com/babeledit) might be of help (7 days free trial!), but absolutely not necessary to achieve this goal.

**Comment by Mortefal** [comment]
This issue has been finished for current translations in the applications, however is still relevant as new features is added to the project
