### ISSUE TITLE
🤯 Change/add logo

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#59]
## Description

Add change logo to (original logo on Slack#general):

<img width=128 src="https://user-images.githubusercontent.com/18369201/53575102-2a633a00-3b71-11e9-9b17-7d34b37c459b.png"/>

- [x] `README.md`
- [x] `assets`
- [x] `src/components/Landing/index.js`

**Comment by PetterRein** [comment]
Logo added to develop
