### ISSUE TITLE
🐛 Compile error in develop

### ISSUE THREAD

**Issue by toretefre** [ecatch-kyst/web#61]
After pulling latest develop (1st of March 11am local time)
## Expected Behavior

Build should build

## Current Behavior

When visiting localhost:3000, this error is shown:

```
Build error: in ./src/components/Forms/components/DropdownMap.jsx

Cannot find file: 'dropdown.json' does not match the corresponding name on disk: './src/components/Forms/components/Dropdown.json'.
```

## Possible Solution

Renaming the import in DropdownMap.jsx makes the build compile, but you are then faced with blank page when trying to post departure message.

## Steps to Reproduce

1. git fetch 
2. git checkout develop
3. git pull
4. yarn
5. yarn start

## Suggestions
@balazsorban44 suggested that @elfingar may have a fix ready already, is that correct?

**Comment by elfingar** [comment]
Its probably a difference in operating systems. A quick fix for now is to change the import in InputForms from `import Dropdown from './components/Dropdown' ` to `import Dropdown from './components/Dropdown.jsx'`. the `.jsx` should make it compile correctly

**Comment by toretefre** [comment]
As the import error is with the dropdown.**json** file and not the dropdown.**jsx** i'm guessing that the fix won't work. Will investigate some more.

**Comment by elfingar** [comment]
I checked it, compiled it and it worked :)

**Comment by toretefre** [comment]
So did I, and it didn't work. Tried just now with the same result.

However, I managed to find a workaround, which was to rename the `Dropdown.json` file and all references into `dropdownlist.json`, to avoid the name conflict with `Dropdown.jsx`. 

Will make a PR to develop for this fix, and see if it works for everyone, as this may be an issue only for MacOS users.

Thanks for helping out!

**Comment by Mortefal** [comment]
Is this done?

**Comment by balazsorban44** [comment]
I would wait with it. Working on something, which will affect this anyway.
