### ISSUE TITLE
✨ Able to login when offline

### ISSUE THREAD

**Issue by PetterRein** [ecatch-kyst/web#68]
Right now you cannot login when you are offline. The pages is loaded but the request to firebase cannot be done.
This may be solved with this: https://firebase.google.com/docs/auth/web/service-worker-sessions

## Expected Behavior

When you are offline and you sign in you will be able to

## Priority

Medium

## Size

1 hour

**Comment by balazsorban44** [comment]
https://firebase.google.com/docs/auth/web/auth-state-persistence

**Comment by PetterRein** [comment]
Our firebase login session is set to never be cleared.

So long the users do not clear browser data their session will be in the browser and they will be automatically logged in
