### ISSUE TITLE
✨ Add to Home Screen

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#8]
PWA means that we need a notification to users that the website can be installed to the home screen.

Things to consider: https://developers.google.com/web/fundamentals/app-install-banners/
 - [x] images
 - [x] service worker with fetch()
 - [x] https

## Expected Behavior

When the website is visited on chrome for more than 30 seconds the user shall get a "notification" in site that tells the user that the website is possible to add to home screen. If the users choose so, the website will be added to home screen and if the users open the site from home screen the website will look like a native app,

## Areas affected

- [x] frontend?

## Priority

When we have time

## Size

1

**Comment by balazsorban44** [comment]
@Virkz looks like the images you added have different names than in the `manifest.json`. Also the `favicon.ico` is not matching either. Check out this https://realfavicongenerator.net

- [x] create all the assets
- [ ] use the dualog colors for the app theme (#6d8c9b, #98dad4)
- [x] update `public/index.html`

NOTE: Don't use a black background, rather a transparent (or white, if necessary).

**Comment by Mortefal** [comment]
@Virkz Is this issues ready to be closed?

**Comment by PetterRein** [comment]
The issue is still open becuase it uses the wrong assets (self made) and not the assets the customer what to use.

The issue remains open until we get the right assets, but all the code and everything is ready.
