### ISSUE TITLE
✨ When a user creates a account, a "Start guide" should help setting settings.

### ISSUE THREAD

**Issue by Mortefal** [ecatch-kyst/web#84]
When first creating the account, a user should get a page where he is asked to fill in what type of gear he's using, his home port etc. This should only come the first time the user creates the account!
## Priority

Not a priority right now. Additional feature

## Size

3

**Comment by balazsorban44** [comment]
https://react-joyride.com/ can be useful..?

**Comment by PetterRein** [comment]
This will like not be done in Sprint 4 because it will not be prioritized

**Comment by PetterRein** [comment]
The user now is redirected to Preset page the first time he uses the application on a device

**Comment by PetterRein** [comment]
In the future maybe and a modal that tells the user why he gets redirected to preset and want it does.

Maybe also add a full walkthrough
