### ISSUE TITLE
✨ Dark mode 🌃🔦

### ISSUE THREAD

**Issue by balazsorban44** [ecatch-kyst/web#9]
- [x] add basic toggle
- [x] add translations (label, and description of the functionality)
- [ ] add options (eg.: use sunset & sunrise, or give period like from 22:00 until 06:00)
- [x] remember the user's decision throughout sessions
- [x] add tests

add both `light` ad `dark` themes for Material-UI (https://github.com/ecatch-kyst/web/blob/feature/dark-mode/src/lib/material-ui.js) NOTE: theming probably deserves its own issue.

## Expected Behavior

When fishermen out on the sea in the middle of the night, it would be practical to provide a darker theme throughout the application.

SIDENOTE: It can also improve battery life.

## Priority

Not important, but nice to have.

## Size

2

**Comment by balazsorban44** [comment]
@Mortefal could you propose a better Norwegian 🇳🇴 translation on line 14?
https://github.com/ecatch-kyst/web/blob/66aea0932573841a6f5a2da1df22b65f8a1a37fd/src/locales/no/pages.json#L9-L16

**Comment by Mortefal** [comment]
@balazsorban44 How about: "Bytt til nattmodus for å gjøre det bedre å bruke appen om natten.", or something similar?

**Comment by Mortefal** [comment]
On the remaining option, that dark-mode should be enabled between 22 pm and 6 am, is this a feature we want to implement? Perhaps we can make it an option in "Advanced settings" or something similar.

**Comment by balazsorban44** [comment]
Yep, not a priority at least. So it can wait.
