### ISSUE TITLE
✨ Validate inputs in frontend

### ISSUE THREAD

**Issue by toretefre** [ecatch-kyst/web#90]
Make sure that forms cannot be submitted without mandatory data.

## Expected Behavior

As an example, the DEP form should not be sent to the server if departure port is missing, or if no time and date has been selected.
Needed on both DEP, DCA and POR. validate all fields.

- [ ] DEP
- [ ] DCA
- [ ] POR
- [ ] TESTTT

## Priority

Before delivery

## Size

1-2?

**Comment by PetterRein** [comment]
https://github.com/JedWatson/react-select/issues/1453
